// Code generated by github.com/actgardner/gogen-avro/v8. DO NOT EDIT.
/*
 * SOURCE:
 *     telemetryData.avsc
 */
package avro

import (
	"io"

	"github.com/actgardner/gogen-avro/v9/vm"
	"github.com/actgardner/gogen-avro/v9/vm/types"
)

func writeArrayTelemetryData(r []TelemetryData, w io.Writer) error {
	err := vm.WriteLong(int64(len(r)), w)
	if err != nil || len(r) == 0 {
		return err
	}
	for _, e := range r {
		err = writeTelemetryData(e, w)
		if err != nil {
			return err
		}
	}
	return vm.WriteLong(0, w)
}

type ArrayTelemetryDataWrapper struct {
	Target *[]TelemetryData
}

func (_ *ArrayTelemetryDataWrapper) SetBoolean(v bool)                { panic("Unsupported operation") }
func (_ *ArrayTelemetryDataWrapper) SetInt(v int32)                   { panic("Unsupported operation") }
func (_ *ArrayTelemetryDataWrapper) SetLong(v int64)                  { panic("Unsupported operation") }
func (_ *ArrayTelemetryDataWrapper) SetFloat(v float32)               { panic("Unsupported operation") }
func (_ *ArrayTelemetryDataWrapper) SetDouble(v float64)              { panic("Unsupported operation") }
func (_ *ArrayTelemetryDataWrapper) SetBytes(v []byte)                { panic("Unsupported operation") }
func (_ *ArrayTelemetryDataWrapper) SetString(v string)               { panic("Unsupported operation") }
func (_ *ArrayTelemetryDataWrapper) SetUnionElem(v int64)             { panic("Unsupported operation") }
func (_ *ArrayTelemetryDataWrapper) Get(i int) types.Field            { panic("Unsupported operation") }
func (_ *ArrayTelemetryDataWrapper) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *ArrayTelemetryDataWrapper) Finalize()                        {}
func (_ *ArrayTelemetryDataWrapper) SetDefault(i int)                 { panic("Unsupported operation") }
func (r *ArrayTelemetryDataWrapper) NullField(i int) {
	panic("Unsupported operation")
}

func (r *ArrayTelemetryDataWrapper) AppendArray() types.Field {
	var v TelemetryData
	v = NewTelemetryData()

	*r.Target = append(*r.Target, v)
	return &types.Record{Target: &(*r.Target)[len(*r.Target)-1]}
}
